controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50.0

    skid_steer_controller:
      type: "skid_steer_drive_controller/SkidSteerDriveController"
      left_front_wheel_names: ["left_wheel_front_joint"]
      left_rear_wheel_names: ["left_wheel_rear_joint"]
      right_front_wheel_names: ["right_wheel_front_joint"]
      right_rear_wheel_names: ["right_wheel_rear_joint"]
      wheel_separation: 0.35
      wheel_radius: 0.05
      cmd_vel_timeout: 0.25
      publish_rate: 100.0
      base_frame_id: "base_link"
      use_stamped_vel: false      
      velocity_rolling_window_size: 10   # Smoothing window for velocity estimates
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]



